version: '3.1'

services:

  postgres:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    volumes:
      - /Users/florafan/IdeaProjects/challenge01/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres

  challenge:
    image: floraff/challenges:0.0.1
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: test
    depends_on:
      - postgres

