spring:
    datasource:
        url: jdbc:postgresql://host.docker.internal:5432/test
        driver-class-name: org.postgresql.Driver
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

